dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.1
compiler:
  solc:
    remappings:
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.1'
dotenv: .env
networks:
  sepolia:
    provider: https://sepolia.infura.io/v3/${WEB3_INFURA_PROJECT_ID}
wallets:
  from_key: ${PRIVATE_KEY}
